spring:
  application:
    name: project

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE?oracle.jdbc.defaultNChar=true
    username: hr
    password: hr

  jpa:
    generate-ddl: true
    database: oracle
    show-sql: true

server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      force: true