spring:
  application:
    name: project

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@M6F:1521:XE
    username: hr
    password: hr

  jpa:
    generate-ddl: true
    database: oracle
    show-sql: true

server:
  port: 8081